# Generated by Django 2.2.2 on 2019-06-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField(blank=True)),
                ('dst', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('owner', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('img_url', models.TextField(blank=True)),
                ('price', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('created_at', models.TextField(blank=True)),
                ('updated_at', models.TextField(blank=True)),
            ],
        ),
    ]
