# Generated by Django 2.2.2 on 2019-06-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='time',
            field=models.TextField(blank=True),
        ),
    ]
