# Generated by Django 2.2.2 on 2019-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='buyer',
            field=models.TextField(blank=True),
        ),
    ]
