# Generated by Django 2.2 on 2019-06-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_stuff_buyer'),
        ('app', '0003_chat_stuff_id'),
    ]

    operations = [
    ]
